# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 220d0fbb45958d1391731bb172dc0a38cfd94e9bddecde5df10e3aeeb622352ba9e8ad9e6b81106966ba72b9a5eb3800880402749aac0eb01da8271e3dfab622

test:
  secret_key_base: 27bf07379de9f1166c7ffd0594f35a08aa01ba5ad8d0a7a41f409dcbc750a88f27cd321c55cc6d6d021026a89987b6df565823c18506c3514ba07a4eb01abfbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
